// mockData
export const sampleReviews = [
  // restaurantId: 1 (오레노 라멘)
  {
    id: 1,
    restaurantId: 1,
    profileImgUrl: "/restaurant/avatar1.png",
    userId: "Alex",
    createdDate: "2025.05.05",
    votes: 20,
    rating: 5,
    content: "이거 먹으려고 부산에서 왔어요",
    tags: ["저녁식사", "혼밥", "고급스러운", "가격대 있음"],
  },
  {
    id: 2,
    restaurantId: 1,
    profileImgUrl: "/restaurant/avatar2.png",
    userId: "Keren",
    createdDate: "2025.05.04",
    votes: 32,
    rating: 4,
    content: "맛있어요",
    tags: ["점심식사", "데이트"],
  },
  {
    id: 3,
    restaurantId: 1,
    profileImgUrl: "/restaurant/avatar3.png",
    userId: "Jack",
    createdDate: "2025.06.03",
    votes: 2,
    rating: 4,
    content: "먹을만 해요",
    tags: ["조용한"],
    images: [
      "/restaurant_blank.png",
      "/restaurant_blank.png",
      "/restaurant_blank.png",
      "/restaurant_blank.png",
    ],
  },

  // restaurantId: 2 (더 모닝 브런치)
  {
    id: 4,
    restaurantId: 2,
    profileImgUrl: "/restaurant/avatar1.png",
    userId: "Eunji",
    createdDate: "2025.06.7",
    votes: 9,
    rating: 5,
    content:
      "여기 에그베네딕트 진짜 미쳤어요. 커피도 맛있고 조용해서 혼자 책 읽기 좋아요.",
    tags: ["브런치", "혼밥", "조용한", "커피맛집"],
  },
  {
    id: 5,
    restaurantId: 2,
    profileImgUrl: "/restaurant/avatar2.png",
    userId: "Minho",
    createdDate: "2025.06.10",
    votes: 3,
    rating: 4,
    content: "분위기 좋고 깔끔했어요. 다만 웨이팅이 좀 있었어요.",
    tags: ["데이트", "깔끔한", "웨이팅 있음"],
  },
  {
    id: 6,
    restaurantId: 2,
    profileImgUrl: "/restaurant/avatar3.png",
    userId: "Soojin",
    createdDate: "2025.06.09",
    votes: 25,
    rating: 4,
    content: "아보카도 샐러드랑 수플레 팬케이크 최고예요. 자주 오고 싶어요.",
    tags: ["아침식사", "건강한", "재방문의사"],
  },
];
