export const initialFoodList: {
  title: string;
  isExcluded: boolean;
  imageUrl?: string | null;
}[] = [
  {
    title: "치킨",
    isExcluded: false,
    imageUrl: "/image/image_empty.svg",
  },
  { title: "초콜릿", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "김밥", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "떡볶이", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "라면", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "삼겹살", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "불고기", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "된장찌개", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "피자", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "햄버거", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "초밥", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "우동", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "쌀국수", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "냉면", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "샐러드", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "바나나", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "딸기", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "요거트", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "도넛", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "커피", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "스테이크", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "순대", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "오므라이스", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "카레", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "비빔밥", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "오징어볶음", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "잡채", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "토스트", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "파스타", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "리조또", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "김치찌개", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "부대찌개", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "샌드위치", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "탕수육", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "깐풍기", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "마라탕", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "양꼬치", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "월남쌈", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "감자튀김", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "계란말이", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "콩나물국밥", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "갈비탕", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "설렁탕", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "육개장", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "새우튀김", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "고로케", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "미트볼", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "베이글", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "팬케이크", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "프렌치토스트", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "크로와상", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "똠얌꿍", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "볶음밥", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "계란찜", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "닭발", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "닭갈비", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "조개구이", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "멕시칸타코", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "타코야끼", isExcluded: false, imageUrl: "/logo/logo.png" },
  { title: "찹쌀떡", isExcluded: false, imageUrl: "/logo/logo.png" },
];
