// mockFoodReviewData.ts
import { FoodReviewCardProps } from "@/app/components/common/FoodReveiwCard";

export const mockFoodReviewCardData: FoodReviewCardProps[] = [
  {
    id: 1,
    createdAt: "2025-07-08",
    restaurantName: "Bean Around the World Coffees",
    rating: 4.5,
    reviewText: "브런치가 맛있어요",
    recommendCount: 24,
    isLiked: false,
    onLikeToggle: () => {
      console.log("좋아요 토글!");
    },
    restaurantImage: "/mypage/my-activity/dummy/sampleImg1.png",
    reviewImages: [],
    tags: ["저녁식사", "혼밥", "캐주얼한"],
    onDelete: () => {
      console.log("삭제됨!");
    },
    onNavigate: () => {
      console.log("맛집 상세 페이지 이동!");
    },
  },
  {
    id: 2,
    createdAt: "2025-07-10",
    restaurantName: "Pier",
    rating: 3.0,
    reviewText:
      "커리가 맛있어요. 커리가 맛있어요. 커리가 맛있어요. 커리가 맛있어요.",
    recommendCount: 24,
    isLiked: true,
    onLikeToggle: () => {
      console.log("좋아요 토글!");
    },
    restaurantImage: "/mypage/my-activity/dummy/sampleImg2.png",
    reviewImages: [
      "/mypage/my-activity/dummy/sampleImg3.png",
      "/mypage/my-activity/dummy/sampleImg4.png",
      "/mypage/my-activity/dummy/sampleImg5.png",
    ],
    tags: ["저녁식사", "혼밥", "캐주얼한"],
    onDelete: () => {
      console.log("삭제됨!");
    },
    onNavigate: () => {
      console.log("맛집 상세 페이지 이동!");
    },
  },
  {
    id: 3,
    createdAt: "2025-07-12",
    restaurantName: "우정횟집",
    rating: 4.5,
    reviewText: "회가 정말 싱싱하고 분위기도 좋아요!",
    recommendCount: 42,
    isLiked: true,
    onLikeToggle: () => {
      console.log("좋아요 토글 - 우정횟집");
    },
    onDelete: () => {
      console.log("삭제됨 - 우정횟집");
    },
    onNavigate: () => {
      console.log("이동 - 우정횟집");
    },
    restaurantImage: "/logo/logo.svg",
    reviewImages: ["/logo/logo.svg", "/logo/logo.svg"],
    tags: ["신선한 해산물", "분위기 좋은", "단골 맛집"],
  },
  {
    id: 4,
    createdAt: "2025-07-20",
    restaurantName: "Pier",
    rating: 3.0,
    reviewText: "커리가 맛있어요. 또 가고 싶어요.",
    recommendCount: 12,
    isLiked: true,
    onLikeToggle: () => {
      console.log("좋아요 토글 - Pier");
    },
    onDelete: () => {
      console.log("삭제됨 - Pier");
    },
    onNavigate: () => {
      console.log("이동 - Pier");
    },
    restaurantImage: "/logo/logo.svg",
    reviewImages: ["/logo/logo.svg", "/logo/logo.svg", "/logo/logo.svg"],
    tags: ["저녁식사", "혼밥", "캐주얼한"],
  },
  {
    id: 5,
    createdAt: "2025-07-03",
    restaurantName: "한우사랑",
    rating: 4.5,
    reviewText: "고기가 부드럽고 서비스도 좋아요!",
    recommendCount: 31,
    isLiked: false,
    onLikeToggle: () => {
      console.log("좋아요 토글 - 한우사랑");
    },
    onDelete: () => {
      console.log("삭제됨 - 한우사랑");
    },
    onNavigate: () => {
      console.log("이동 - 한우사랑");
    },
    restaurantImage: "/logo/logo.svg",
    reviewImages: ["/logo/logo.svg", "/logo/logo.svg"],
    tags: ["고급", "데이트", "고기 맛집"],
  },
  {
    id: 8,
    createdAt: "2025-07-16",
    restaurantName: "바다향기",
    rating: 5.0,
    reviewText: "회가 아주 신선했어요!",
    recommendCount: 6,
    isLiked: false,
    restaurantImage: "/logo/logo.svg",
    reviewImages: ["/logo/logo.svg", "/logo/logo.svg"],
    tags: ["해산물", "뷰 맛집"],
    onLikeToggle: () => console.log("좋아요 토글!"),
    onDelete: () => console.log("삭제됨!"),
    onNavigate: () => console.log("맛집 상세 페이지 이동!"),
  },
  {
    id: 9,
    createdAt: "2025-07-01",
    restaurantName: "맛집 9",
    rating: 5.0,
    reviewText: "정말 맛있었어요!",
    recommendCount: 46,
    isLiked: false,
    restaurantImage: "/logo/logo.svg",
    reviewImages: ["/logo/logo.svg"],
    tags: ["맛있어요", "친절해요", "재방문 의사 있음"],
    onLikeToggle: () => console.log("좋아요 토글!"),
    onDelete: () => console.log("삭제됨!"),
    onNavigate: () => console.log("맛집 상세 페이지 이동!"),
  },
  {
    id: 10,
    createdAt: "2025-07-12",
    restaurantName: "맛집 10",
    rating: 1.0,
    reviewText: "정말 맛있었어요!",
    recommendCount: 39,
    isLiked: true,
    restaurantImage: "/logo/logo.svg",
    reviewImages: ["/logo/logo.svg"],
    tags: ["맛있어요", "친절해요", "재방문 의사 있음"],
    onLikeToggle: () => console.log("좋아요 토글!"),
    onDelete: () => console.log("삭제됨!"),
    onNavigate: () => console.log("맛집 상세 페이지 이동!"),
  },
  {
    id: 11,
    createdAt: "2025-07-14",
    restaurantName: "맛집 11",
    rating: 2.0,
    reviewText: "정말 맛있었어요!",
    recommendCount: 5,
    isLiked: false,
    restaurantImage: "/logo/logo.svg",
    reviewImages: ["/logo/logo.svg"],
    tags: ["맛있어요", "친절해요", "재방문 의사 있음"],
    onLikeToggle: () => console.log("좋아요 토글!"),
    onDelete: () => console.log("삭제됨!"),
    onNavigate: () => console.log("맛집 상세 페이지 이동!"),
  },
  {
    id: 12,
    createdAt: "2025-07-17",
    restaurantName: "맛집 12",
    rating: 3.0,
    reviewText: "정말 맛있었어요!",
    recommendCount: 42,
    isLiked: true,
    restaurantImage: "/logo/logo.svg",
    reviewImages: ["/logo/logo.svg"],
    tags: ["맛있어요", "친절해요", "재방문 의사 있음"],
    onLikeToggle: () => console.log("좋아요 토글!"),
    onDelete: () => console.log("삭제됨!"),
    onNavigate: () => console.log("맛집 상세 페이지 이동!"),
  },
  {
    id: 13,
    createdAt: "2025-07-05",
    restaurantName: "맛집 13",
    rating: 4.0,
    reviewText: "정말 맛있었어요!",
    recommendCount: 41,
    isLiked: false,
    restaurantImage: "/logo/logo.svg",
    reviewImages: ["/logo/logo.svg"],
    tags: ["맛있어요", "친절해요", "재방문 의사 있음"],
    onLikeToggle: () => console.log("좋아요 토글!"),
    onDelete: () => console.log("삭제됨!"),
    onNavigate: () => console.log("맛집 상세 페이지 이동!"),
  },
  {
    id: 14,
    createdAt: "2025-07-17",
    restaurantName: "맛집 14",
    rating: 5.0,
    reviewText: "정말 맛있었어요!",
    recommendCount: 1,
    isLiked: true,
    restaurantImage: "/logo/logo.svg",
    reviewImages: ["/logo/logo.svg"],
    tags: ["맛있어요", "친절해요", "재방문 의사 있음"],
    onLikeToggle: () => console.log("좋아요 토글!"),
    onDelete: () => console.log("삭제됨!"),
    onNavigate: () => console.log("맛집 상세 페이지 이동!"),
  },
  {
    id: 15,
    createdAt: "2025-07-12",
    restaurantName: "맛집 15",
    rating: 1.0,
    reviewText: "정말 맛있었어요!",
    recommendCount: 33,
    isLiked: false,
    restaurantImage: "/logo/logo.svg",
    reviewImages: ["/logo/logo.svg"],
    tags: ["맛있어요", "친절해요", "재방문 의사 있음"],
    onLikeToggle: () => console.log("좋아요 토글!"),
    onDelete: () => console.log("삭제됨!"),
    onNavigate: () => console.log("맛집 상세 페이지 이동!"),
  },
  {
    id: 16,
    createdAt: "2025-07-01",
    restaurantName: "맛집 16",
    rating: 2.0,
    reviewText: "정말 맛있었어요!",
    recommendCount: 17,
    isLiked: true,
    restaurantImage: "/logo/logo.svg",
    reviewImages: ["/logo/logo.svg"],
    tags: ["맛있어요", "친절해요", "재방문 의사 있음"],
    onLikeToggle: () => console.log("좋아요 토글!"),
    onDelete: () => console.log("삭제됨!"),
    onNavigate: () => console.log("맛집 상세 페이지 이동!"),
  },
  {
    id: 17,
    createdAt: "2025-07-04",
    restaurantName: "맛집 17",
    rating: 3.0,
    reviewText: "정말 맛있었어요!",
    recommendCount: 44,
    isLiked: false,
    restaurantImage: "/logo/logo.svg",
    reviewImages: ["/logo/logo.svg"],
    tags: ["맛있어요", "친절해요", "재방문 의사 있음"],
    onLikeToggle: () => console.log("좋아요 토글!"),
    onDelete: () => console.log("삭제됨!"),
    onNavigate: () => console.log("맛집 상세 페이지 이동!"),
  },
  {
    id: 18,
    createdAt: "2025-07-04",
    restaurantName: "맛집 18",
    rating: 4.0,
    reviewText: "정말 맛있었어요!",
    recommendCount: 14,
    isLiked: true,
    restaurantImage: "/logo/logo.svg",
    reviewImages: ["/logo/logo.svg"],
    tags: ["맛있어요", "친절해요", "재방문 의사 있음"],
    onLikeToggle: () => console.log("좋아요 토글!"),
    onDelete: () => console.log("삭제됨!"),
    onNavigate: () => console.log("맛집 상세 페이지 이동!"),
  },
  {
    id: 19,
    createdAt: "2025-07-08",
    restaurantName: "맛집 19",
    rating: 5.0,
    reviewText: "정말 맛있었어요!",
    recommendCount: 41,
    isLiked: false,
    restaurantImage: "/logo/logo.svg",
    reviewImages: ["/logo/logo.svg"],
    tags: ["맛있어요", "친절해요", "재방문 의사 있음"],
    onLikeToggle: () => console.log("좋아요 토글!"),
    onDelete: () => console.log("삭제됨!"),
    onNavigate: () => console.log("맛집 상세 페이지 이동!"),
  },
  {
    id: 20,
    createdAt: "2025-07-03",
    restaurantName: "맛집 20",
    rating: 1.0,
    reviewText: "정말 맛있었어요!",
    recommendCount: 40,
    isLiked: true,
    restaurantImage: "/logo/logo.svg",
    reviewImages: ["/logo/logo.svg"],
    tags: ["맛있어요", "친절해요", "재방문 의사 있음"],
    onLikeToggle: () => console.log("좋아요 토글!"),
    onDelete: () => console.log("삭제됨!"),
    onNavigate: () => console.log("맛집 상세 페이지 이동!"),
  },
];
