have_fun: false  # 장난스러운 멘트/톤 비활성화

code_review:
  disable: false  # 코드 리뷰 기능 활성화
  comment_severity_threshold: MEDIUM  # 최소 MEDIUM 수준 이상 문제에만 댓글 작성
  max_review_comments: -1  # 리뷰 댓글 수 무제한

  pull_request_opened:
    help: false       # PR 생성 시 도움말 제공 비활성화
    summary: false    # 요약 제공 비활성화
    code_review: true  # PR 오픈 시 자동 리뷰 실행

ignore_patterns:
  - '.github/'     # 워크플로우 관련 파일 무시
  - '.husky/'      # Git hook 설정 무시
  - '.storybook/'  # Storybook 설정 파일 무시
  - '.vscode/'     # 편집기 설정 무시
